config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments, only: [:new, :create]
  end

  get   "/signup" => "registrations#new", as: :signup
  post  "/signup" => "registrations#create"

  get   "/signin" => "authentication#new", as: :signin
  post  "/signin" => "authentication#create"

  get   "/signout" => "authentication#destroy", as: :signout

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password
  validates :email, uniqueness: { case_sensitive: false }, presence:true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if !current_user
      redirect_to signin_path, notice: "You must be signed in to do that!"
    end
  end

  helper_method :current_user, :authenticate_user
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully signed in"
    else
      redirect_to signin_path, alert: "Username / password combination is invalid"
    end
  end

  def new
    @user = User.new
  end

  def destroy
    session.destroy
    redirect_to root_path, notice: "You have been signed out"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(body: params[:comment][:body])
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @post
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :destroy, :edit]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find_by(id: params[:id])
    if !@post
      redirect_to post_path(params[:id]), notice: "You can't edit that!"
    end
  end

  def update
    @post = current_user.posts.find_by(id: params[:id])
    if @post
      @post.update(post_params)
      redirect_to root_path, notice: "Your post was updated"
    end
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    if @post
      @post.destroy
      redirect_to root_path, notice: "Post deleted!"
    else
      redirect_to root_path, notice: "You can't delete that!"
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You have been successfully signed up!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :password,
    :password_confirmation
    )

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<div class="col-lg-8 col-lg-offset-2">
  <h1 class="page-header">Sign In</h1>

  <%= form_tag signin_path, class: "form-horizontal" do %>

  <div class="form-group">
    <div class="col-md-4 col-md-offset-2">
      <%= text_field_tag :email, nil, placeholder: "Email", class: "form-control", id: "email-field" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 col-md-offset-2">
      <%= password_field_tag :password, nil, placeholder: "Password", class: "form-control", id: "password-field" %>
    </div>
  </div>

  <div class="actions">
    <%= submit_tag "Sign In", id:"user-login-action", class: "btn btn-primary col-md-offset-2" %>
  </div>

  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p><%= comment.body %> - comment by <strong><%= comment.user.username %></strong></p>
  </div>
</div>

app/views/comments/new.html.erb
<h3>Add a Comment</h3>
<hr>
<%= form_for [@post, @comment], html: {class: "form-horizontal"} do |f| %>
<div class="form-group">
  <div class="col-xs-8">
    <%= f.text_area :body, size: "10x4", class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-xs-4">
    <%= f.submit "Add Comment", class: "btn btn-md btn-primary btn-block" %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloneReddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <% if notice %>
    <div id="notice" class="alert alert-success">
      <%= notice %>
    </div>
    <% end %>

    <% if alert %>
    <div class="alert alert-danger">
      <%= alert %>
    </div>
    <% end %>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <% if current_user %>
        <p class="current-user">Signed in as <%= current_user.username %> | <%= link_to "Sign Out", signout_path, id:"signout-action" %>
        </p>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", signup_path, id: "signup-action" %></li>
          <li><%= link_to "Sign In", signin_path, id: "signin-action" %></li>
        </ul>
        <% end %>
      </div>


    </nav>

    <div class="jumbotron">
      <h1>
        <%= link_to "g", root_path, :class =>"navbar-brand" %>
        | Reddit
      </h1>
    </div>

    <%= yield %>

  </div>
</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= form_for @post, html: { class: "form-horizontal" } do |f| %>
<hr

<div class="form-group">
  <%= f.label :title, class: "sr-only" %>
  <div class="col-xs-6">
    <%= f.text_field :title, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :body, class: "sr-only" %>
  <div class="col-xs-6">
    <%= f.text_field :body, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-xs-6">
    <%= f.submit class: "btn btn-md btn-primary btn-block" %>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>Recent Posts</h2>
  <hr>
  <% @posts.each do |post| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to post.title, post %>
      <p>
        posted <%= time_ago_in_words(post.created_at) %> ago -  by
        <%= post.user.username %>
      </p>
    </div>
  </div>
  <% end %>
</div>

<%= link_to "Post something", new_post_path, class: "btn btn-primary" %>

app/views/posts/new.html.erb
<h2>Create A Post</h2>
<hr>
<%= form_for @post, html: {class: "form-horizontal"} do |f| %>
<div class="form-group">
  <%= f.label :title, class: "sr-only" %>
  <div class="col-xs-6">
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :body, class: "sr-only" %>
  <div class="col-xs-6">
    <%= f.text_field :body, placeholder: "Body", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-xs-6">
    <%= f.submit class: "btn btn-md btn-primary btn-block" %>
  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <h3><%= @post.title %>
      <small>- Posted by <%= @post.user.username %> - <%= @post.created_at.strftime("%b %d, %Y") %></small>
    </h3>
    <p>
      <%= @post.body %>
    </p>
    <div class="comments">
      <% if @post.comments.present? %>
      <%= render @post.comments %>
    </div>
    <% end %>
  </div>
</div>
</div>
<footer>
  <%= link_to "Back", root_path %> |

  <% if current_user %>
  <%= link_to "Add Comment", new_post_comment_path(@post) %> |
  <% end %>

  <% if current_user && @post.user_id == current_user.id %>
  <%= link_to "Edit", edit_post_path(@post)  %> |
  <%= link_to "Delete", @post, method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
  <% end %>
</footer>

app/views/shared/_errors.html.erb
<% if instance.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <h2><%= pluralize(instance.errors.count, "error") %> prohibited this <%= instance.class %> from being saved:</h2>

  <ul>
    <% instance.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>